# 행렬
- 행렬의 항등원 - 단위 행렬을 곱하면 - 대각선으로 1인 행렬

In [2]:
import numpy as np
print(np.__version__)
print(np.eye(5))
print(np.identity(5))

1.19.2
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# 행렬을 메모리에 저장하는 방법
- 행 우선
- 열 우선

In [3]:
first= np.ndarray(shape=(2,2), dtype=float, order='F') # fortran style (열 우선)
first # 메모리는 쓰레기 초기화

array([[4.45036200e+217, 2.25563609e-153],
       [3.31006788e-258, 3.52287686e-110]])

In [4]:
first.fill(10)
first

array([[10., 10.],
       [10., 10.]])

In [7]:
print(np.zeros((3,4)))
print(np.ones((2,3,4),dtype=np.int16)) # 대량의 데이터
print(np.full((2,2),7))
print(np.eye(4))
print(np.empty((4,2)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000]
 [0.00e+000 5.91e-321]
 [0.00e+000 0.00e+000]]


In [8]:
import numpy as np
# python core 연속된 수 range : list
# arange = vector
array = np.arange(10).reshape(5,2)
# [0.......9]
print("원배열 : \n", array)

b = np.ones_like(array, float)
print("\n동일 사이즈행렬: \n",b)

원배열 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

동일 사이즈행렬: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
c = np.arange(10)
print(c)
print(type(c))
c_copy = c[0:5].copy() # deep copy
print(c_copy)

c_copy[0:2]=100
print(c)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


In [11]:
e = np.arange(24).reshape(2,3,4)
print(e)
print(e.flatten())
e = np.arange(24).reshape(1,2,3,4) # 24개의 요소
print("차원확대")
print(e)
print("차원축소")

e=e.reshape(-1,4) # 나머지다 : 6이 된다
print(e)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
차원확대
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]
차원축소
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [12]:
e.shape

(6, 4)

In [13]:
e.dtype

dtype('int32')

In [14]:
e.ndim

2

In [15]:
e.dtype.byteorder

'='

In [16]:
e.dtype.itemsize # 4바이트

4

In [17]:
e.astype(np.float32)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]], dtype=float32)

In [18]:
a = np.arange(0,100,10)
indices = [1,5,-1]
print(indices)
b = a[indices]
print(a)
print(b)

[1, 5, -1]
[ 0 10 20 30 40 50 60 70 80 90]
[10 50 90]


In [21]:
# 데이터는 메모리에 연속해서 저장
print("스트라이드의 값", np.ones((3,4,5), dtype=np.float64).strides)
# 한 열은 8바이트를 지나면 있다.
# 40바이트를 지나가면 행이 바뀐다.
# 160이 지나가면 면이 바뀐다.

스트라이드의 값 (160, 40, 8)


In [19]:
arr2d = np.array(([1,2,3], [4,5,6],[7,8,9]))# shape 3,3
print(arr2d[0])
print(arr2d[0][2])
print(arr2d[0,2])
print(arr2d[:2])
print(arr2d[:2,1:])
print(arr2d[1,:2])
print(arr2d[2,:1])
arr2d[:2,:1]=0

print(arr2d)
print(arr2d.ndim)
print(arr2d.nbytes)
print(arr2d.strides)

[1 2 3]
3
3
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[4 5]
[7]
[[0 2 3]
 [0 5 6]
 [7 8 9]]
2
36
(12, 4)


In [28]:
# 다음과 같이 데이터를 저장하고
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d = np.arange(1,13).reshape(2,2,3)
#- 첫면을 출력
#- 첫면 첫행을 출력
#- 첫면 첫행 첫요소를 출력
#- 숫자 8을 출력
#- 숫자 12를 출력

In [29]:
print(arr3d[0])
print(arr3d[0][0])
print(arr3d[0][0][0])
print(arr3d[1][0][1])
print(arr3d[1][1][2])

[[1 2 3]
 [4 5 6]]
[1 2 3]
1
8
12


In [30]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [32]:
print(arr[[1,5,7,2],[0,3,1,2]])

print("파이프")
print(arr[[1,5,7,2]][[0,3,1]])

print("팬시")
print(arr[[1,2,5,7]][:,[0,1,2,3]])
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[ 4 23 29 10]
파이프
[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]]
팬시
[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [58]:
a=np.arange(0,51,10)
list=[]
for i in range(len(a)):
    list.append(np.arange(a[i],a[i]+6))

In [61]:
list

[array([0, 1, 2, 3, 4, 5]),
 array([10, 11, 12, 13, 14, 15]),
 array([20, 21, 22, 23, 24, 25]),
 array([30, 31, 32, 33, 34, 35]),
 array([40, 41, 42, 43, 44, 45]),
 array([50, 51, 52, 53, 54, 55])]

In [81]:
print([list[0][2],list[2][2],list[5][2]])
print(list[0,1,2,3,4],[])

[2, 22, 52]


TypeError: list indices must be integers or slices, not tuple

In [111]:
list = []
for i in range(0,6):
    a = []
    for j in range(0,6):
        a.append(i*10+j)
    list.append(a)
aa = np.array(list)

In [113]:
aa

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [114]:
aa[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [115]:
arr=np.arange(32).reshape((8,4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [116]:
arr@arr #행렬곱 기호 8,4 , 8,4 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 8 is different from 4)

In [117]:
arr.T # 전치 행렬

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [118]:
arr@arr.T

array([[  14,   38,   62,   86,  110,  134,  158,  182],
       [  38,  126,  214,  302,  390,  478,  566,  654],
       [  62,  214,  366,  518,  670,  822,  974, 1126],
       [  86,  302,  518,  734,  950, 1166, 1382, 1598],
       [ 110,  390,  670,  950, 1230, 1510, 1790, 2070],
       [ 134,  478,  822, 1166, 1510, 1854, 2198, 2542],
       [ 158,  566,  974, 1382, 1790, 2198, 2606, 3014],
       [ 182,  654, 1126, 1598, 2070, 2542, 3014, 3486]])

In [123]:
np.transpose(arr)

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [119]:
np.matmul(arr, arr.T)

array([[  14,   38,   62,   86,  110,  134,  158,  182],
       [  38,  126,  214,  302,  390,  478,  566,  654],
       [  62,  214,  366,  518,  670,  822,  974, 1126],
       [  86,  302,  518,  734,  950, 1166, 1382, 1598],
       [ 110,  390,  670,  950, 1230, 1510, 1790, 2070],
       [ 134,  478,  822, 1166, 1510, 1854, 2198, 2542],
       [ 158,  566,  974, 1382, 1790, 2198, 2606, 3014],
       [ 182,  654, 1126, 1598, 2070, 2542, 3014, 3486]])

In [120]:
arr.T@arr

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])

In [122]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)
v = np.array([1,0,1])
#
print("타일출력")
vv = np.tile(v, (4, 1))
print(vv)
# 행렬연산 요소연산
y = x + vv
print(y)

print(x+v) # 브로드캐스팅 (반드시 말단 차수가 일치해야함)
x + 3

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
타일출력
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [124]:
arr = np.arange(24).reshape((2,3,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [125]:
print(arr.transpose((1,0,2))) # 3,2,4

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


In [126]:
print(arr.transpose((0,2,1)))#2, 4, 3

[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


In [2]:
import numpy as np
names = np.array(['Seoul', 'Daejun', 'chungju', 'seoul', 'chungju', 'Daejun', 'Daejun'])
# 정규분포에서 표준편차 2배수 안에 있을 확률 : 95%
# 3배수 안에 있을 확률 : 99%
# 6 sigma운동
data = np.random.randn(7,4) # normal 정규 분포

print(names=='Seoul')

print(data[names=='Seoul']) # boolean인덱싱은 브로드캐스팅이 안됨
print(data[names=='Seoul',2:])
print(data[names=='Seoul',3])

print(names != 'Seoul')
print(~(names == 'Seoul'))
mask = (names == 'Seoul') | (names=='chungju')
print(mask)
print(data[mask])

[ True False False False False False False]
[[-0.56865127  0.35390692 -0.40836018 -0.43879294]]
[[-0.40836018 -0.43879294]]
[-0.43879294]
[False  True  True  True  True  True  True]
[False  True  True  True  True  True  True]
[ True False  True False  True False False]
[[-0.56865127  0.35390692 -0.40836018 -0.43879294]
 [ 0.01728804  0.67671206 -0.7761293   1.75261225]
 [ 2.76833076 -1.72935348 -2.05738804  1.17407936]]


In [3]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
print(zip(xarr, yarr, cond))
print(list(zip(xarr, yarr, cond)))
result = [(x if c else y) for x,y,c in zip(xarr,yarr,cond)]
print("result = ",result)

[(1.1, 2.1, True), (1.2, 2.2, False), (1.3, 2.3, True), (1.4, 2.4, True), (1.5, 2.5, False)]
result =  [1.1, 2.2, 1.3, 1.4, 2.5]


In [4]:
# 벡터화 연산 - core

In [5]:
result = np.where(cond, xarr, yarr)
print(result)

arr = np.random.randn(4,4)
print(arr)
print(np.where(arr>0, 2, -2))
print(np.where(arr>0, 2, arr))

[1.1 2.2 1.3 1.4 2.5]
[[-1.36704861 -1.93023554  1.74467718 -1.62572384]
 [ 0.5137336  -0.19215394  0.305615    0.71386855]
 [ 0.36451354  1.47228906 -1.29803261  0.19391143]
 [ 0.67320794  0.52290339 -0.44153892 -0.24650445]]
[[-2 -2  2 -2]
 [ 2 -2  2  2]
 [ 2  2 -2  2]
 [ 2  2 -2 -2]]
[[-1.36704861 -1.93023554  2.         -1.62572384]
 [ 2.         -0.19215394  2.          2.        ]
 [ 2.          2.         -1.29803261  2.        ]
 [ 2.          2.         -0.44153892 -0.24650445]]


# 문제 
- cond1 = np.array([1,0,1,1,0,0,1], dtype=bool)
- cond2 = np.array([0,1,1,1,0,1,1], dtype=bool)
- 두개 다 참이면 0, cond1이 참이면 1 cond2가 참이면 2, 그 외일 때는 3으로 처리하여 출력하시오

In [1]:
import numpy as np
cond1 = np.array([1,0,1,1,0,0,1], dtype=bool)
cond2 = np.array([0,1,1,1,0,1,1], dtype=bool)
cond3 = np.array([0,0,0,0,0,0,0], dtype=bool)
a=np.where((cond1==1),1,cond1)
b=np.where((cond2==1),2,cond2)
print(list(zip(a,b)))

[(1, 0), (0, 2), (1, 2), (1, 2), (0, 0), (0, 2), (1, 2)]


In [7]:
#두개가 참 1참 2참 둘다 낫참 3
result = [(x if y==x+1 else 0) for x,y,z in zip(cond1,cond2,cond3)]

In [14]:
result=np.where(cond1 & cond2, 0, np.where(cond1,1,np.where(cond2,2,3)))
result

array([1, 2, 0, 0, 3, 2, 0])

In [15]:
result = 1*(cond1 & ~cond2) + 2*(cond2 & ~cond1) + 3* ~(cond1 | cond2)
print("수식을 이용한", result)

수식을 이용한 [1 2 0 0 3 2 0]


In [17]:
arr1 = np.arange(4)
arr4 = np.arange(2)
print(arr1)
print(arr4)
arr2 = np.arange(8).reshape(4,2)
print(arr2)
arr3d = np.array([arr2, arr2, arr2])
print(arr3d)
print(arr3d + arr3d)
print(arr3d + arr2)
print(arr3d + arr4)

[0 1 2 3]
[0 1]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[[0 1]
  [2 3]
  [4 5]
  [6 7]]

 [[0 1]
  [2 3]
  [4 5]
  [6 7]]

 [[0 1]
  [2 3]
  [4 5]
  [6 7]]]
[[[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]]

 [[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]]

 [[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]]]
[[[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]]

 [[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]]

 [[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]]]
[[[0 2]
  [2 4]
  [4 6]
  [6 8]]

 [[0 2]
  [2 4]
  [4 6]
  [6 8]]

 [[0 2]
  [2 4]
  [4 6]
  [6 8]]]


In [21]:
# 복사 하지 않고 1차원으로 표현
# deep copy후에 별도의 공간에서 1차원으로 변환하기 때문에 불변
import numpy as np
a1 = np.array([[5,6],
               [7,8]])
ra = a1.ravel()
re = a1.reshape(-1)
fl = a1.flatten()
print(ra,re,fl)
a1[0][0]=100
print(ra,re,fl)
import math

[5 6 7 8] [5 6 7 8] [5 6 7 8]
[100   6   7   8] [100   6   7   8] [5 6 7 8]


In [43]:
from numpy import math
print(math.ceil(1.100))
print(math.floor(1.100))
print(math.factorial(5))
print(math.gcd(10,125))
print(math.trunc(1.001))
print(math.trunc(1.999))

2
1
120
5
1
1


In [19]:
print("abs(-11) : ",abs(-11))

abs(-11) :  11


In [22]:
print("math.e : ", math.e)

math.e :  2.718281828459045


In [24]:
print("pow(2,10) : ",pow(2,10))

pow(2,10) :  1024


In [25]:
print("divmod(10,7) : ", divmod(10,7))

divmod(10,7) :  (1, 3)


In [26]:
x = np.arange(9).reshape((3,3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [27]:
theta = np.linspace(0, np.pi,3)

In [30]:
# 반지름이 1인 원의 가로 세로 비율을 통해서 각도나 길이를 알 수 있다.
# 삼각함수는 가로 세로의 비율
print("theta : " , theta)
print("sin(theta) : " , np.sin(theta))
print("cos(theta) : " , np.cos(theta))
print("tan(theta) : " , np.tan(theta))

theta :  [0.         1.57079633 3.14159265]
sin(theta) :  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) :  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) :  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [45]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x)) # 일이 자연대수 : 은행 예금의 변화
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [47]:
import numpy as np
from numpy import linalg as la
x = np.array([1.0,1.0])
print("2차원",la.norm(x))
x = np.array([1.0,1.0,1.0])
print("3차원",la.norm(x))

2차원 1.4142135623730951
3차원 1.7320508075688772


In [49]:
a = np.array([[1,2],[3,4]])
print(a)
b = np.array([[11,12],[13,14]])
print(b)
np.dot(a,b)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]


array([[37, 40],
       [85, 92]])

In [52]:
A = np.arange(2*3*4).reshape((2,3,4))
B = np.arange(2*4*3).reshape((2,4,3))
print(A)
print(B)
print("행렬곱 :", np.matmul(A,B))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
행렬곱 : [[[  42   48   54]
  [ 114  136  158]
  [ 186  224  262]]

 [[ 906  960 1014]
  [1170 1240 1310]
  [1434 1520 1606]]]


In [53]:
x + y = 2
y + z = 2
x + y + z = 3

# [[1,1,0],[0,1,1],[1,1,1]] * [x,y,z] = [2,2,3]
# [x,y,z] = [2.2.3] / [[1,1,0],[0,1,1],[1,1,1]]
# 행렬 나눗셈이 없음
# 역행렬을 구해서 해를 구함

SyntaxError: cannot assign to operator (<ipython-input-53-4f0e88bf32ce>, line 1)

In [61]:
A = np.array([[1,1,0],[0,1,1],[1,1,1]])
Alnv = np.linalg.inv(A) # inv : inverse matrix
b = np.array([[2],[2],[3]])
b
x = Alnv @ b
x

array([[1.],
       [1.],
       [1.]])

In [ ]:
2x + y -2z = -3
3x + z = 5
x + y -z = -2

In [62]:
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
Alnv = np.linalg.inv(A)
b = np.array([[-3],[5],[-2]])
x = Alnv @ b
x

array([[ 1.],
       [-1.],
       [ 2.]])

In [64]:
np.matmul(np.linalg.inv(A),b)

array([[ 1.],
       [-1.],
       [ 2.]])

In [65]:
x = np.linalg.solve(A,b)
x

array([[ 1.],
       [-1.],
       [ 2.]])

In [66]:
a = np.array([0,1,0])
b = np.array([1,0,0])
res=np.dot(a,b)
print(res)
print(np.linalg.norm(a))
print(np.linalg.norm(b))
print(np.linalg.norm(a) * np.linalg.norm(b))
rad = res / (np.linalg.norm(a) * np.linalg.norm(b))
print("cos theta", rad)
print(np.arccos(rad))
print(np.degrees(np.arccos(rad)))

0
1.0
1.0
1.0
cos theta 0.0
1.5707963267948966
90.0


In [70]:
from statistics import *
x=np.array([7,8,9])
y= np.array([9,10,20])
print(y.mean())
print(np.median(y))
print(np.corrcoef(x,y)) # 상관 계수 행렬 : 정방행렬, 대칭행렬

666666666666673.0
10.0
[[1.        0.8660254]
 [0.8660254 1.       ]]


In [68]:
print("공분산",np.cov(x,y)) # covariance

# cov = sigma((x-xbar)(y-ybar)/(n-1))         xbar,ybar : 평균
# corr = cov / (xsigma * ysigma)

# 상관계수의 의미가 내적과 같다

공분산 [[ 1.   5.5]
 [ 5.5 37. ]]


In [71]:
arr=np.array(([1,2,3],[4,5,6],[7,8,9]))
print("원본",arr)
print("누적합(행)=",arr.cumsum(0)) # 행방향
print("누적곱(열)=",arr.cumprod(1)) # 열방향

print("배열의 합계=",arr.sum())
print("열방향으로 합계(행평균) =", arr.mean(axis=1))
print("행방향으로의 합계=", arr.sum(0))

원본 [[1 2 3]
 [4 5 6]
 [7 8 9]]
누적합(행)= [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
누적곱(열)= [[  1   2   6]
 [  4  20 120]
 [  7  56 504]]
배열의 합계= 45
열방향으로 합계(행평균) = [2. 5. 8.]
행방향으로의 합계= [12 15 18]


In [77]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print("범위", np.ptp(a))
print("열범위", np.ptp(a, axis=1)) # peak to peak : range 범위 값
print("분위수", np.percentile(a,50)) # 위치적으로 중위수
# 통계학 : 중위수를 사용 - 이상치에 강건하다. 백분위수 (중간에 있는 것)
print(np.percentile(a,50, axis=1))
print("행중위수",np.median(a, axis=0))
print("열평균", np.mean(a, axis = 1))

범위 7
열범위 [4 5 7]
분위수 4.0
[5. 4. 4.]
행중위수 [3. 4. 5.]
열평균 [5. 5. 5.]


In [80]:
a = np.array([1,2,3,4])
wts = np.array([4,3,2,1])
print(np.average(a,weights = wts))
# 표준편차 구하는 식
std = np.sqrt(np.mean(abs(a-a.mean())**2))
print(std)
# 제곱근((모든 데이터 - 평균)**2)
print(np.mean(abs(a-a.mean())**2))
print (np.var([1,2,3,4]))
print(np.std(a))

2.0
1.118033988749895
1.25
1.25
1.118033988749895


In [ ]:
pandas : numpy + dict(중복허용, 순서를 보장) + 함수형프로그래밍(map, filter, reduce) + 데이터베이스(group by) + 엑셀(pivot)
    + 시계열분석(index 기능 )
- 인덱스 : 열중심
- numpy (행중심, 열중심 (F) )
- [행,열] : loc(키), iloc(숫자)
- 행:사람 열:성적  : 열내 동질적 열간이질적
- Serise(1차원, 데이터 프레임의 열), DataFrame(2차원 행과 열)
- 행과 열의 인덱스 : 검색을 고속으로 하기 위해서

In [83]:
import pandas as pd
data = pd.Series([0.25,0.5,0.75,1.0,], index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [84]:
data['b']

0.5

In [85]:
data[1]

0.5

In [86]:
'a' in data

True

In [87]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [88]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [89]:
data['e']=1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [90]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [91]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [92]:
data[(data>0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [94]:
data[['a','e']]

a    0.25
e    1.25
dtype: float64

In [95]:
data = pd.Series(['a','b','c'], index=[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [96]:
data[1:3]

3    b
5    c
dtype: object

In [97]:
data.loc[1] # 키

'a'

In [98]:
data.loc[1:3]

1    a
3    b
dtype: object

In [99]:
data.iloc[1] # 인덱스

'b'

In [140]:
area = pd.Series({'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135})
data = pd.DataFrame({'area': area, 'pop': pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [141]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [142]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [143]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [144]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [145]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [146]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [147]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [148]:
# 문제 density가 100보다 큰 pop, density열을 출력하시오
# 0번행 2번열의 값을 90으로 변경해보시오

In [151]:
data.loc[data['density']> 100,'pop':]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [153]:
data.iloc[0,2]=90

In [154]:
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [3]:
import pandas as pd
import numpy as np
data1 = {'state': ['경기', '강원', '서울', '충북', '인천'], 'year':[2000,2001,2002,2001,2002],'pop':[1.5,1.7,3.6,2.4,2.9]}

# 1)위의 데이터를 데이터 프레임으로 생성 인덱스는 one two three four five
# 2)state만 출력
# 3)debt 열 추가 하고 모든값 16.5
# 4)파생변수 'estern'에 주소가 서울인가를 따져 서울이면 True 아니면 False를 입력
# 5)debt열에 대하여 (-1.2, -1.5, -1.7) index=['two','four','five']로 된 시리즈를 만들고 대체
# 합계 출력
# 모든행의 데이터 설명

In [4]:
data1=pd.DataFrame(data1,index=['one','two','three','four','five'])
data1

state  year  pop
one      경기  2000  1.5
two      강원  2001  1.7
three    서울  2002  3.6
four     충북  2001  2.4
five     인천  2002  2.9

In [5]:
data1['state']

one      경기
two      강원
three    서울
four     충북
five     인천
Name: state, dtype: object

In [6]:
data1.loc[:,'debt']= [16.5,16.5,16.5,16.5,16.5]
data1

state  year  pop  debt
one      경기  2000  1.5  16.5
two      강원  2001  1.7  16.5
three    서울  2002  3.6  16.5
four     충북  2001  2.4  16.5
five     인천  2002  2.9  16.5

In [7]:
data1['estern'] = np.where(data1['state']=='서울', 'True','False')
data1

state  year  pop  debt estern
one      경기  2000  1.5  16.5  False
two      강원  2001  1.7  16.5  False
three    서울  2002  3.6  16.5   True
four     충북  2001  2.4  16.5  False
five     인천  2002  2.9  16.5  False

In [8]:
aaa=pd.Series([-1.2, -1.5, -1.7],index=['two','four','five'])
data1['debt']= aaa
data1['debt']['one']=16.5
data1['debt']['three']=16.5
data1

<ipython-input-8-30e63783b606>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['debt']['one']=16.5
<ipython-input-8-30e63783b606>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['debt']['three']=16.5


state  year  pop  debt estern
one      경기  2000  1.5  16.5  False
two      강원  2001  1.7  -1.2  False
three    서울  2002  3.6  16.5   True
four     충북  2001  2.4  -1.5  False
five     인천  2002  2.9  -1.7  False

In [9]:
data1.sum()

state                   경기강원서울충북인천
year                         10006
pop                           12.1
debt                          28.6
estern    FalseFalseTrueFalseFalse
dtype: object

In [231]:
print(data1.describe().T)
print(data1.state.value_counts())

      count         mean       std     min     25%     50%      75%     max
year    5.0  2001.200000  0.836660  2000.0  2001.0  2001.0  2002.00  2002.0
pop     5.0     2.420000  0.864292     1.5     1.7     2.4     2.90     3.6
debt    3.0    -1.466667  0.251661    -1.7    -1.6    -1.5    -1.35    -1.2
서울    1
경기    1
인천    1
강원    1
충북    1
Name: state, dtype: int64


In [ ]:
- 문제 다음 데이터를 데이터프레임에 저장하시요
-        지역  2018    2017    2016    2015       2015-2018 증가율
- 서울 수도권  9904312 9631482 9762546 9853972    0.0283
- 부산 경상권  3448737 3393191 3512547 3655437    0.0163
- 인천 수도권  2890451 2632035 2517680 2466338    0.0982
- 대구 경상권  2466052 2431774 2456016 2473990    0.0141 

In [19]:
ji=pd.DataFrame({'서울': ['수도권',9904312,9631482,9762546,9853972,0.0283],
            '부산': ['경상권',3448737,3393191,3512547,3655437,0.0163],
            '인천': ['수도권',2890451,2632035,2517680,2466338,0.0982],
            '대구': ['경상권',2466052,2431774,2456016,2473990,0.0141]},
                index=['지역','2018','2017','2016','2015','2015-2018 증가율'],
                columns=["서울","부산","인천","대구"])
ji.T

지역     2018     2017     2016     2015 2015-2018 증가율
서울  수도권  9904312  9631482  9762546  9853972        0.0283
부산  경상권  3448737  3393191  3512547  3655437        0.0163
인천  수도권  2890451  2632035  2517680  2466338        0.0982
대구  경상권  2466052  2431774  2456016  2473990        0.0141

In [20]:
ji = ji.T

In [21]:
ji.dtypes

지역               object
2018             object
2017             object
2016             object
2015             object
2015-2018 증가율    object
dtype: object

In [22]:
ji['2015']=ji["2015"].astype('float')
ji['2016']=ji["2016"].astype('float')
ji['2017']=ji["2017"].astype('float')
ji['2018']=ji["2018"].astype('float')

In [23]:
ji["2015-2017 증가율"] = ((ji["2017"] - ji["2015"]) / ji["2015"]*100).round(2)
ji

지역       2018       2017       2016       2015 2015-2018 증가율  \
서울  수도권  9904312.0  9631482.0  9762546.0  9853972.0        0.0283   
부산  경상권  3448737.0  3393191.0  3512547.0  3655437.0        0.0163   
인천  수도권  2890451.0  2632035.0  2517680.0  2466338.0        0.0982   
대구  경상권  2466052.0  2431774.0  2456016.0  2473990.0        0.0141   

    2015-2017 증가율  
서울          -2.26  
부산          -7.17  
인천           6.72  
대구          -1.71